---

- name: generate nise data
  hosts: localhost
  gather_facts: false
  vars:
    ilts:
      - start_date: 2019-08-19
        end_date: 2019-08-23
      - start_date: 2019-08-19
        end_date: 2019-08-23
      - start_date: 2019-08-26
        end_date: 2019-08-30

      - start_date: 2019-09-02
        end_date: 2019-09-06
      - start_date: 2019-09-02
        end_date: 2019-09-06
      - start_date: 2019-09-09
        end_date: 2019-09-13
      - start_date: 2019-09-16
        end_date: 2019-09-20
      - start_date: 2019-09-23
        end_date: 2019-09-27

  tasks:
    - name: ILTs AWS
      template:
        src: ./templates/aws_gpte_sample_ILT.j2
        dest: ./static-report-files/aws_gpte_sample_ILT.yaml

    - name: ILTs OCP
      template:
        src: ./templates/ocp_gpte_sample_ILT.j2
        dest: ./static-report-files/ocp_gpte_sample_ILT.yaml

    - name: csplit ocpfiles so they can be imported as separate clusters
      shell: 'csplit -f "ocp_sample_" -n4 -b "%04d.yaml"  ocp_gpte_sample_ILT.yaml /---/ {*}'
      args:
        chdir: static-report-files/

    - name: generate data from aws static-report-files
      debug:
        msg: skipping generate data from aws static-report-files

    - name: generate data from ocp static-report-files
      debug:
        msg: skipping generate data from ocp static-report-files
